name: SwiftOnMac-dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-26

    steps:
      - name: install dependencies
        run: brew install gsl uv pyenv pyenv-virtualenv
      - uses: actions/checkout@v5
      - uses: SwiftyLab/setup-swift@latest
      - name: Build
        run: swift build
      - name: Run tests
        run: |
          uv sync
          uv tool update-shell
          eval "$(pyenv virtualenv-init -)"
          source .venv/bin/activate
          swift test

